sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - $HOME/bin
    - node_modules

rvm:
  - 2.3.1
env:
  global:
    - TRAVIS_NODE_VERSION="node"
  secure: "g29bP0AizPVIKz0OXKdNjrc1/aS8GnfRTrJ8b6IJJ8L8qaWBXMP6DpfV6lkXUihdKGi8FyNjINBXGyyOzytbbpOU/uDOB+LnU2kxMvdhw3mD+Ku3FETqKqpSEoLV9XFdAY5Jgnvdgj4MbDy0M1LPJaOxpSmNcUsdl2PjXvbDMscuobchQdozHnjB1N06YguANxRxO7YujVe9XvXtFP3J9EcpJOl9DP3ZKKi3sys+NGMiL/Hp9AyJLJRAaPudB+MhdiMHUHJV+c1KgjAgNcF4o+IOIZx0kRHvZOLapABi81Beb9nnpHFokWaMmaP9QpWX7jbMNTtKgV1vNu1In1Ap7POGLCboMBWu0UVbw7i8v1AeUzhxC06ik6zbVZwpwNkoIxzdZWPrXPn/QFEAr66oZc3McE+y2DS43sP9h+AXYPKkeDsGuHOGR+vElC6ehXcjIBP5AccCFJ+ZmhQZGriiMoJWM0Z44OrdOd0xZThqLGF7IJjdSlh8mKnkCXWblVVciLMQY5jTTjLmWnwrgkoD9POIWnX5+wflguKV5xx8RXzMlUkz1w6GwoeaC7/O9QyUm+7I7dxd9lNJ/SGFGB5YDTYpWGw8jAAQWQpBtayYNBUqY8J6x5r9B2RjYMD6Kesp80guipORh2Hayds0kbIkDpik4iLkzp7TFWqpOdu/tEw="

before_install:
  - mkdir -p "$HOME/bin"
  - export PATH="$HOME/bin:$PATH"
  - [ -f "$HOME/bin/stout" ] || wget https://github.com/EagerIO/Stout/releases/download/v1.2.3/stout-linux -O "$HOME/bin/stout"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - bundle install --path vendor/bundle

script:
  - "./bin/middleman build"

deploy:
  skip_cleanup: true
  provider: script
  script: stout deploy
  on:
    branch: master

notifications:
  email: false
  flowdock:
    secure: "scbmHlvyA7gO5dBVkiyguJ1vTGAtDyT6nT7SyAftIxujlScW76AbUoFJjbyTVxZ0lXt1fXPSojnJzn75iN4vJ9v+aLs8bAdPOwPeNkw9o3rQLH/fVlMwIDaEMrBZE549coDSaiV6BZPbuiNJ2JASOK0r5T9bXw1gvAYGQ6j68+1ueiwm0+HsEMUF3xPIRnU5oGrZjee1W4lrm4G8wflVe8Km0Um2Eckqt5tPz63FoEXZNnMG5UeaBdef9VUuWYWFtA7WsJVICmGEfiVrAdS76rvTOwsg7m+/ITpw7F59clbygt5HHD/KxwvBrpjzJ7SQPGL5U5Be1BwTtVo5ld1tacJdF0GXuP1DA8z1gb37x1sYLNJjqXq7nx1/WbaTetOxjPfDQ2CbDJyKjvspcsi1yN3daYfobhUkEU1KqtUgBnHKq3QvM2wrQ2qaOFOhhvrBtYNAH5oK69s8ehqVc8J/TZypHANAnfGxraXQfz8v9wA/mLa6BT7yHUlQxUjkiFexxC5HQRjpkfRPxDKTVKeg3akXN1P/sCCezlj4XIbYp3YrjslHts0J3mEsw6mbc+ZQKuSmEU0ylZ/EB9N2QiRksvUwXIsSZH6moeCdRz990AFYceHesDY4q43YPgxzBQAgZUNT755qwaFW84CUzSkxR3st0bRwklwzfE6Up8PXI6w="
