sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - $HOME/bin

rvm:
  - 2.3.1
env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - secure: "qK/GUJ3fqB3HGjiT8X+opU2nppzy62LL+ZkfyCuEo0Cscyfw4oQ8GCkY0FLLRGz6tkVIoFZHfVRxqKZDCt2PstOaOrBPYxhKa3ObozYBh7zSSRunPjcBPUYM9y5+Jg7CZ2+lVraLukEeexaXUbJ3XUFocYvhkpZPAXOBUywuXeOQV5uLu4TXwxmv9QtUh0cTvF4r7xVn9FJC8qK/OfXv0IJ4/ETqEFZD48T3I/NU7dvzimYcAhmkdRGnAuR7LTwcwjjpkrnKLLicHGiegNCYhzZ8OuL5e3Co35y0CBN4LRwSl0PDubesNTpr23TnglEMISX4MfJKQgU5mgW2MNagYR0MinJNTB1YqTziUzKpIEYDUhr+bMXUTe+p1kXjQSOCjXeLWWQkirX0ULJ32tmJo73CIUjXNpYY3DYru3hpMR0GRUoZsDO3B4/7EO2XAY1+LFlMrXsQRTqOcsEGZqAIdP5tnhGWOoMrSD7nw6aihFnq4E4cFtiCAM4xXQBi9cvahJ4LIcedyVx6QkHhMb8EEZdvIdL8Isvxc1+/CBNm2sWeq7E0hlvwykc3RFH/cqts6892mjdjhKiEQMutQiD999NNhpcyLwuGnHuHKDLft3XRlXMosmBIxfON1cscdHI+8efvZJ1o4Dmgs/xjz9v0hgsjYf3u9WG/Suq/DCPsyM4="

before_install:
  - mkdir -p "$HOME/bin"
  - export PATH="$HOME/bin:$PATH"
  - '[ -f "$HOME/bin/stout" ] || wget https://github.com/EagerIO/Stout/releases/download/v1.2.3/stout-linux -O "$HOME/bin/stout"'
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - bundle install --path vendor/bundle

script:
  - "./bin/middleman build"

deploy:
  skip_cleanup: true
  provider: script
  script: ./bin/deploy.sh
  on:
    branch: master

notifications:
  email: false
  flowdock:
    secure: "scbmHlvyA7gO5dBVkiyguJ1vTGAtDyT6nT7SyAftIxujlScW76AbUoFJjbyTVxZ0lXt1fXPSojnJzn75iN4vJ9v+aLs8bAdPOwPeNkw9o3rQLH/fVlMwIDaEMrBZE549coDSaiV6BZPbuiNJ2JASOK0r5T9bXw1gvAYGQ6j68+1ueiwm0+HsEMUF3xPIRnU5oGrZjee1W4lrm4G8wflVe8Km0Um2Eckqt5tPz63FoEXZNnMG5UeaBdef9VUuWYWFtA7WsJVICmGEfiVrAdS76rvTOwsg7m+/ITpw7F59clbygt5HHD/KxwvBrpjzJ7SQPGL5U5Be1BwTtVo5ld1tacJdF0GXuP1DA8z1gb37x1sYLNJjqXq7nx1/WbaTetOxjPfDQ2CbDJyKjvspcsi1yN3daYfobhUkEU1KqtUgBnHKq3QvM2wrQ2qaOFOhhvrBtYNAH5oK69s8ehqVc8J/TZypHANAnfGxraXQfz8v9wA/mLa6BT7yHUlQxUjkiFexxC5HQRjpkfRPxDKTVKeg3akXN1P/sCCezlj4XIbYp3YrjslHts0J3mEsw6mbc+ZQKuSmEU0ylZ/EB9N2QiRksvUwXIsSZH6moeCdRz990AFYceHesDY4q43YPgxzBQAgZUNT755qwaFW84CUzSkxR3st0bRwklwzfE6Up8PXI6w="
